version: '3.4'

services:
  istatplab2:
    image: ${DOCKER_REGISTRY-}istatplab2
    build:
      context: .
      dockerfile: istatplab2/Dockerfile
    depends_on:
      - sqlserverService
    networks:
      - musicnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
  sqlserverService:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: sqlserverService
    container_name: sqlserverService
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Soficus123!
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - 1433:1433
    networks:
      - musicnet

networks:
  musicnet:
    driver: bridge